version: '3'
services:
  born.postgres.db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  born.web:
    build: .
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/born-back
    ports:
      - "3000:3000"
    depends_on:
      - born.postgres.db